name: Run Colab Hourly
on:
  schedule:
    - cron: "0 20 * * *"  # Every hour at minute 0
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert papermill
          
      - name: Run notebook
        run: |
          jupyter nbconvert --execute --to notebook --inplace your_notebook.ipynb
          # Alternative using papermill:
          # papermill your_notebook.ipynb CPCB.ipynb
