name: Execute CPCB Notebook
on:
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twilio pandas requests jupyter nbconvert papermill geopandas plotly matplotlib
          
      - name: Convert and clean notebook
        run: |
          # Convert notebook to .py file explicitly
          jupyter nbconvert --to script CPCB_new.ipynb --output-dir . --output CPCB_script
          
          # Clean the generated script
          sed -i '/^!/d' CPCB_script.txt  # Remove shell commands
          sed -i '/^%matplotlib/d' CPCB_script.txt  # Remove magic commands
          mv CPCB_script.txt CPCB_script.py  # Rename to .py
          
      - name: Execute script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          DESTINATION_PHONE: ${{ secrets.DESTINATION_PHONE }}
        run: |
          python CPCB_script.py
          
    
