name: Execute CPCB Notebook
on:
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twilio pandas requests jupyter nbconvert
          
      - name: Convert and clean notebook
        run: |
          # Convert notebook and remove magic commands
          jupyter nbconvert --to script CPCB.ipynb --output CPCB_script
          sed -i '/^!/d' CPCB_script.py
          sed -i '/^%matplotlib/d' CPCB_script.py
          
      - name: Execute script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          DESTINATION_PHONE: ${{ secrets.DESTINATION_PHONE }}
        run: |
          python CPCB_script.py

