name: Test Schedule

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute (UTC)
  workflow_dispatch:      # 👈 Add this to allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: echo "Triggered at $(date)"
